apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
   envFrom:
    -configMapRef:
        name: dev-db 