apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myfirstpod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
   envFrom:
    -configMapRef:
        name: dev-db 